[Paths]

# RECOMMENDED: Set the media_folder to the directory containing your video file.
# The script will auto-detect the video and subtitle files within this folder.
media_folder = /home/radeksz/Downloads/torrents/


[Tasks]
# Master Switches (True/False). Run any combination of tasks independently.
analyze_video = False
transcode_video = False
download_subtitles = False
process_subtitles = True

[VideoSettings]
# Target framerate for subtitle shifting/converting
fps = 23.976

[SubtitleProcessing]
# Subtitle shift in milliseconds (negative = backwards, positive = forward)
# 1 second == 1000 ms
shift_ms = 0

# Processing modules toggles (True/False).
fix_encoding = True
sanitize_text = True
convert_to_srt = True